"""rename department

Revision ID: f81963b3d0fc
Revises: 6b8f20eae6ae
Create Date: 2024-08-23 15:12:07.329287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81963b3d0fc'
down_revision = '6b8f20eae6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
